services:
  default: 
    build: .
    init: true
    command: tail -f /dev/null
    cpus: 2.0
    network_mode: bridge
    working_dir: /workspace
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - TZ=Etc/UTC

